### ISSUE TITLE
本地节点如何链接到主网

### ISSUE THREAD

**Issue by wyz9527** [nebulasio/wiki#213]
本地节点如何链接到主网，我看了https://github.com/nebulasio/wiki/blob/master/mainnet.md 这个文档 但是没看懂。
如果链接上主网，第一次启动需要同步区块吗？
如果链接上主网，只和主网通信，不挖矿不同步数据 可以吗

**Comment by yupnano** [comment]
首先切换到Master分支，然后运行指令 `./neb -c mainnet/conf/config.conf` 就可以连接主网了.

目前连接主网后会同步全部数据。

**Comment by wyz9527** [comment]
现在主网数据是多大，如果是4核8G内存500G硬盘的阿里云服务器，    同步全部数据大概要花多少时间

**Comment by weiht12** [comment]
你好，此版本为星云旧版wiki（后期逐步停止维护），欢迎将您的问题提交星云新版wiki，以便于获得及时解答。同时，参与wiki的编辑维护工作还会有奖励哦。新版wiki链接：https://wiki.nebulas.io/en/latest/（英文）；https://wiki.nebulas.io/zh_CN/latest/（中文）
Hello, this version is the nebulas old wiki (later stop maintenance), welcome to submit your question to the new nebulas wiki, in order to get timely answers. At the same time, there will be rewards for editing and maintaining the wiki. New wiki link: https://wiki.nebulas.io/en/latest/(English); https://wiki.nebulas.io/zh_CN/latest/(Chinese)
