### ISSUE TITLE
FAQ not complete

### ISSUE THREAD

**Issue by 1c7** [nebulasio/wiki#216]
https://github.com/nebulasio/wiki/blob/master/FAQ.md
![image](https://user-images.githubusercontent.com/1804755/44308667-927bdb00-a3ec-11e8-8772-25c0d9d1a6c4.png)

![image](https://user-images.githubusercontent.com/1804755/44308673-9f003380-a3ec-11e8-9755-6d963dbb12ff.png)

## Suggestion: Remove them all or replace "answer here" with actual answer

**Comment by weiht12** [comment]
你好，此版本为星云旧版wiki（后期逐步停止维护），欢迎将您的问题提交星云新版wiki，以便于获得及时解答。同时，参与wiki的编辑维护工作还会有奖励哦。新版wiki链接：https://wiki.nebulas.io/en/latest/（英文）；https://wiki.nebulas.io/zh_CN/latest/（中文）
Hello, this version is the nebulas old wiki (later stop maintenance), welcome to submit your question to the new nebulas wiki, in order to get timely answers. At the same time, there will be rewards for editing and maintaining the wiki. New wiki link: https://wiki.nebulas.io/en/latest/ (English); https://wiki.nebulas.io/zh_CN/latest/ (Chinese)

**Comment by 1c7** [comment]
明白了
