### ISSUE TITLE
请问合约中如何批量转账?

### ISSUE THREAD

**Issue by xbhuang1994** [nebulasio/wiki#78]
请问合约里如何对不同地址进行批量转账呢？
`
for 
Blockchain.transfer(from, amount)
`
只能用循环这样调用吗？

**Comment by weiht12** [comment]
你好，此版本为星云旧版wiki，欢迎将您的问题提交星云新版wiki，以便于及时与星云开发人员及其他社区开发者进行交流。同时，参与wiki的编辑维护工作还会有奖励哦。新版wiki链接：https://wiki.nebulas.io/en/latest/（英文）；https://wiki.nebulas.io/zh_CN/latest/（中文）
Hello, this version is the nebulas old wiki (later stop maintenance), welcome to submit your question to the new nebulas wiki, in order to get timely answers. At the same time, there will be rewards for editing and maintaining the wiki. New wiki link: https://wiki.nebulas.io/en/latest/(English); https://wiki.nebulas.io/zh_CN/latest/(Chinese)
